apiVersion: v2
name: mongodb
version: 1.0.0
dependencies:
  - name: mongodb
    repository: https://charts.bitnami.com/bitnami
    version: 12.1.15
  - name: mongo-express
    repository: https://cowboysysop.github.io/charts/
    version: 2.6.5
